# Generated by Django 5.2.3 on 2025-07-15 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_remindeer_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
