# Generated by Django 5.2.3 on 2025-06-19 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='until_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
